# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-27 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0004_auto_20170524_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effluent_data',
            name='value_received_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Date Reported'),
        ),
    ]
